#! /bin/sh

# Inicialização
bash ${HOME}/.fehbg
${HOME}/.config/polybar/launch.sh &
picom -cCGfF -o 0.38 -O 200 -I 200 -t 0 -l 0 -r 3 -D2 -m 0.88 &
dunst &
xfce4-power-manager &

pgrep -x sxhkd > /dev/null || sxhkd &

# Áreas de trabalho
bspc monitor -d I II III IV

# Borda
bspc config border_width        3
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Cores
#bspc config normal_border_color "#000000"
bspc config normal_border_color "#3f0057"
#bspc config active_border_color "#000000"
bspc config active_border_color "#3f0057"
#bspc config focused_border_color "#000000"
bspc config focused_border_color "#3f0057"
bspc config presel_feedback_color "#FF0000"

# Regras
bspc rule -a vivaldi-bin desktop='^2' state=tiling follow=on
