export NVM_DIR="$HOME/.nvm"
export PATH=$PATH:$HOME/.local/bin

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
[ -x /bin/fish ] && SHELL=/bin/fish exec fish
