#!/bin/sh

source /etc/profile
export PS1="(chroot) ${PS1}"
cp -r /gentoo/arquivos/portage/{env,package.env,package.use,make.conf,sets} /etc/portage/
cp /gentoo/arquivos/hosts /etc/
cp /gentoo/arquivos/conf.d/keymaps /etc/conf.d/keymaps
fallocate -l4G /swap
chmod 600 /swap
mkswap /swap
swapon /swap
