#!/bin/sh

source /etc/profile
export PS1="(chroot) ${PS1}"

mkdir -p /etc/portage/package.accept_keywords
cp -r /gentoo/arquivos/portage/{env,package.env,package.use,package.mask,make.conf,sets} /etc/portage/
cp /gentoo/arquivos/hosts /etc/
