#!/bin/sh

cat <<EOF
curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
fisher install jorgebucaran/fisher
fisher install jorgebucaran/nvm.fish
fisher install jorgebucaran/nvm.fish
fisher install Gazorby/fish-git-emojis
nvm install lts
EOF
