#!/bin/sh

emerge kde-plasma/plasma-desktop kde-plasma/powerdevil kde-plasma/systemsettings x11-misc/sddm kde-plasma/sddm-kcm kde-plasma/plasma-nm kde-plasma/plasma-pa
# x11-drivers/amdgpu media-libs/vulkan-radeon kde-plasma/kwin
