#!/bin/sh

emerge-webrsync
emerge sys-fs/genfstab app-eselect/eselect-repository app-admin/doas dev-vcs/git app-portage/gentoolkit dev-util/ccache app-portage/eix app-admin/eclean-kernel

rm -rf /var/db/repos/gentoo/
cp -r /gentoo/arquivos/portage/repos.conf /etc/portage
emerge --sync
egencache --jobs=16 --update --repo gentoo
eix-update

eselect profile list

cat << EOF

  eselect profile set X
  emerge -uND @world

EOF
