#!/bin/sh

echo "pt_BR.UTF8 UTF-8" > /etc/locale.gen
echo Gentoo > /etc/hostname

mkdir -p /home/guilherme/.config/fish/
cp /gentoo/arquivos/bashrc /home/guilherme/.bashrc
cp /gentoo/arquivos/config/fish/config.fish /home/guilherme/.config/fish/

cp /gentoo/arquivos/doas.conf /etc/
cp /gentoo/arquivos/conf.d/keymaps /etc/conf.d/
cp -r /gentoo/arquivos/portage/repos.conf /etc/portage
ln -sf ../usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
locale-gen

rm -rf /var/db/repos/gentoo/
emerge --sync

passwd

printf "\n\nExecutar: eselect locale list\nenv-update && source /etc/profile && export PS1='(chroot) ${PS1}'\n\n"
