#!/bin/sh

echo "pt_BR.UTF8 UTF-8" > /etc/locale.gen
#echo "br-abnt2" | tee /etc/conf.d/keymaps
echo Gentoo > /etc/hostname
cp /gentoo/arquivos/doas.conf /etc/
emerge --config sys-libs/timezone-data
locale-gen
passwd
printf "\n\nExecutar: eselect locale list\n\nenv-update && source /etc/profile && export PS1='(chroot) ${PS1}'\n\n"
