#!/bin/sh

echo "pt_BR.UTF8 UTF-8" > /etc/locale.gen
echo Gentoo > /etc/hostname
cp /gentoo/arquivos/doas.conf /etc/
cp /gentoo/arquivos/conf.d/keymaps /etc/conf.d/
cp /gentoo/arquivos/conf.d/display-manager /etc/conf.d/
emerge --config sys-libs/timezone-data
locale-gen
passwd
printf "\n\nExecutar: eselect locale list\n\nenv-update && source /etc/profile && export PS1='(chroot) ${PS1}'\n\n"
