#!/bin/sh

mkdir -p /boot/efi
mount /dev/sda1 /boot/efi
mount /dev/sda3 /home
genfstab -U . >> /etc/fstab
emerge -q  sys-kernel/installkernel-gentoo gentoo-kernel-bin genkernel linux-firmware intel-microcode grub
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=Gentoo --recheck
printf "\n\nExecutar: nano /etc/default/grub e\nnano/etc/fstab"
