#!/bin/sh

echo "pt_BR.UTF8 UTF-8" > /etc/locale.gen
ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
timedatectl set-timezone America/Sao_Paulo
hostnamectl set-hostname Gentoo

printf "\nExecutar: eselect locale list
    nExecutar: localectl set-locale pt_BR.UTF-8"
