#!/bin/sh

make -j8 -l8 -k && make -j8 -l8 -k modules_install && make -j8 -l8 -k install
genkernel --install --kernel-config=.config initramfs
grub-mkconfig -o /boot/grub/grub.cfg
emerge @module-rebuild
